In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_excel("data1.xlsx")
df.head(4)

   year(X)  cost(Y)
0     2005    27911
1     2007    37709
2     2001     8816
3     2009    46048

In [6]:
x=df["year(X)"]
y=df["cost(Y)"]
x=np.array(x)
x=x.reshape(-1,1)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)
from sklearn.linear_model import LinearRegression
clf=LinearRegression()
clf.fit(x_train,y_train.values.ravel())
y_pred=clf.predict(x_test)
y_pred

array([45490.22330573, 20951.58141685, 20951.58141685, 20951.58141685,
       40582.49492796,  6228.39628352, 11136.1246613 , 11136.1246613 ,
       11136.1246613 , 20951.58141685,  6228.39628352, 30767.0381724 ,
       45490.22330573, 50397.95168351, 45490.22330573, 35674.76655018,
       11136.1246613 , 30767.0381724 , 25859.30979463, 40582.49492796,
       30767.0381724 , 25859.30979463, 11136.1246613 , 20951.58141685,
       11136.1246613 , 40582.49492796, 16043.85303907, 45490.22330573,
       25859.30979463, 11136.1246613 , 45490.22330573, 50397.95168351,
       45490.22330573, 11136.1246613 ,  6228.39628352, 11136.1246613 ,
       40582.49492796, 45490.22330573, 30767.0381724 ,  6228.39628352,
       30767.0381724 , 50397.95168351, 11136.1246613 , 40582.49492796,
       25859.30979463, 16043.85303907, 25859.30979463, 16043.85303907,
       40582.49492796, 11136.1246613 , 45490.22330573, 30767.0381724 ,
       11136.1246613 , 25859.30979463, 45490.22330573, 35674.76655018,
       30767.0381724 , 11136.1246613 , 40582.49492796, 45490.22330573,
       35674.76655018, 45490.22330573, 11136.1246613 , 20951.58141685,
       20951.58141685, 20951.58141685, 45490.22330573, 20951.58141685,
       45490.22330573, 45490.22330573, 30767.0381724 , 35674.76655018,
       20951.58141685, 16043.85303907, 16043.85303907,  6228.39628352,
       30767.0381724 , 40582.49492796, 35674.76655018, 45490.22330573,
       16043.85303907, 35674.76655018, 11136.1246613 , 25859.30979463,
        6228.39628352, 30767.0381724 , 30767.0381724 , 11136.1246613 ,
        6228.39628352, 16043.85303907, 35674.76655018, 45490.22330573,
       11136.1246613 , 30767.0381724 , 35674.76655018, 35674.76655018,
        6228.39628352, 20951.58141685, 30767.0381724 , 45490.22330573,
       16043.85303907, 40582.49492796, 25859.30979463, 45490.22330573,
       25859.30979463, 35674.76655018, 11136.1246613 , 20951.58141685,
       50397.95168351, 16043.85303907, 50397.95168351, 40582.49492796,
       20951.58141685, 20951.58141685, 11136.1246613 ,  6228.39628352,
       11136.1246613 , 11136.1246613 , 11136.1246613 , 30767.0381724 ,
       30767.0381724 , 45490.22330573, 16043.85303907, 30767.0381724 ,
       35674.76655018, 16043.85303907, 30767.0381724 , 16043.85303907,
       25859.30979463, 30767.0381724 ,  6228.39628352, 11136.1246613 ,
        6228.39628352, 45490.22330573, 16043.85303907, 25859.30979463,
       20951.58141685,  6228.39628352, 25859.30979463, 45490.22330573,
       20951.58141685, 25859.30979463, 45490.22330573, 16043.85303907,
       20951.58141685, 45490.22330573, 20951.58141685,  6228.39628352,
       35674.76655018, 50397.95168351, 11136.1246613 , 20951.58141685,
       45490.22330573, 16043.85303907, 40582.49492796, 20951.58141685,
       45490.22330573, 16043.85303907, 25859.30979463, 30767.0381724 ,
       40582.49492796, 50397.95168351, 45490.22330573, 25859.30979463,
       45490.22330573])

In [7]:
df=df.drop("year(X)",axis=1)
df.head()

   cost(Y)
0    27911
1    37709
2     8816
3    46048
4     6241

In [8]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
print("r2_score",r2_score(y_test,y_pred))

r2_score 0.9871670522221588

In [9]:
new_year=[[2011]]
x=clf.predict(new_year)
x

array([55305.68006129])